### ISSUE TITLE
An option to enable horizontal wrapping when using a pager

### ISSUE THREAD

**Issue by trustin** [dalance/procs#104]
Hi! Thanks a lot for a neat tool first of all.

One missing feature I want is that there's no way to tell the pager to wrap lines so that I don't have to scroll horizontally.

It would be nice if procs can output like the following:
```
 18092 trustin │         0.0 0.2 00:00:09 │ /opt/my/process --very-long-option=v
               |                          | ery-long-option-value-1
 18130 trustin │         7.8 0.2 00:00:40 │ /opt/my/process --very-long-option=v
               |                          | ery-long-option-value-2
 18160 trustin │         0.0 0.0 00:00:00 │ /opt/my/process --very-long-option=v
               |                          | ery-long-option-value-3
```

instead of:
```
 18092 trustin │         0.0 0.2 00:00:09 │ /opt/my/process --very-long-option=>
 18130 trustin │         7.8 0.2 00:00:40 │ /opt/my/process --very-long-option=>
 18160 trustin │         0.0 0.0 00:00:00 │ /opt/my/process --very-long-option=>
```

Alternatively, it may be nice if I can specify an external pager app, such as `less` and `bat`, which has been configured as I want already.

**Comment by dalance** [comment]
Sorry for the late reply.

External pager can be specified through config.
https://github.com/dalance/procs#pager-section

Wrapping behavior can be specified too.
https://github.com/dalance/procs#display-section

For example, if `cut_to_terminal` is set to `false`, wrapping is enabled.
But the wrapping is not done by each column.

For example:

```
 18092 trustin │         0.0 0.2 00:00:09 │ /opt/my/process --very-long-option=v
ery-long-option-value-1
 18130 trustin │         7.8 0.2 00:00:40 │ /opt/my/process --very-long-option=v
ery-long-option-value-2
 18160 trustin │         0.0 0.0 00:00:00 │ /opt/my/process --very-long-option=v
ery-long-option-value-3
```

Each column wrapping seems to be difficult because the width of column can't be calculated uniquely.

**Comment by trustin** [comment]
Thank you for the detailed answer, @dalance! `cut-to-terminal=false` is just enough for me. Loving `procs` :heart:
